services:
    redis:
        image: redis:5
        ports:
            - '127.0.0.1::6379'
        healthcheck:
            test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
            interval: 10s
            timeout: 5s
            retries: 10

    postgres:
        image: postgres:${POSTGRES_VERSION:-10}-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-app}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
            POSTGRES_USER: ${POSTGRES_USER:-app}
        labels:
            com.symfony.server.service-prefix: 'POSTGRES'
        ports:
            - '127.0.0.1::5432'

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_USER: ${MYSQL_USER:-app}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMe!}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
        labels:
            com.symfony.server.service-prefix: 'MYSQL'
        command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
        ports:
            - '127.0.0.1::3306'
