services:
    Ibexa\Bundle\Messenger\Migration\InstallSchemaMigration:
        autowire: true
        public: false
        arguments:
            $connection: '@ibexa.persistence.connection'
        tags:
            - { name: !php/const Ibexa\Contracts\DoctrineMigrations\Migrations\IbexaMigrationTag::TAG }

    Ibexa\Bundle\Messenger\Migration\FixMessengerMessagesIndexesMigration:
        autowire: true
        autoconfigure: false
        public: false
        arguments:
            $connection: '@ibexa.persistence.connection'
        tags:
            - { name: !php/const Ibexa\Contracts\DoctrineMigrations\Migrations\IbexaMigrationTag::TAG }
