services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ibexa.messenger.serializer:
        class: Ibexa\Bundle\Messenger\Serializer\Serializer
        factory: [ '@Ibexa\Bundle\Messenger\Serializer\SerializerFactory', 'create' ]

    Ibexa\Bundle\Messenger\Serializer\SerializerFactory:
        arguments:
            $normalizers: !tagged_iterator ibexa.messenger.serializer.normalizer
